name: '@Metro Phonix Jew'
favicon: null
layout_spectrum: 0.8027255001943558
typography_spectrum: 0.11200384888797998
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5720417981501669
  lightness: 0.8532925813924521
  saturation: 0.9173438851721585
  rhythmicContrast: 0.9315562590491027
purpose: []
